# Generated by Django 4.1.5 on 2023-01-17 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('temperature', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('api_resource', models.CharField(blank=True, max_length=70, null=True)),
                ('temperature_month_ago', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('temperature_year_ago', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('temperature_yesterday', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('id_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
